---
title: "Free and open source software for transport applications: a review"
author: "Robin Lovelace"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Open source software has grown rapidly over past 3 decades and is now the default option in many fields of research and application, including Computer Science, Machine Learning and, increasingly, the physical and social sciences. However, the broadly defined field of 'Transport Studies', has been a slow adopter. The purpose of this paper is to explore why this is the case and, more constructively, to provide an outline of the emerging landscape of open source software in the field. We find that although none of them are mainstream, there open source tools have been developed to help many aspects of transport research and applications, especially in the fields of modelling and visualisation. Will open source software dominate the Transport Studies in the future? We conclude that there are many opportunities for uptake across the field, with large potential benefits for collaborative research and the democratisation of the transport decision making process.

## Introduction

## Overview of open source software for transport applications

## Opportunities for the future

## Discussion