---
title: "Transport routing with stplanr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{stplanr vignette 3: routing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(stplanr)
```

## This vignette is work in progress - watch this space!


```{r, echo=FALSE, eval=FALSE}
# upload roads data
if(!file.exists("roads_iow.Rds")) {
  download.file("https://github.com/ropensci/stplanr/releases/download/0.3.1/roads_iow.Rds", "roads_iow.Rds")
}
roads_iow = readRDS("roads_iow.Rds")
sf::write_sf(roads_iow, "roads_iow.geojson")
piggyback::pb_upload("roads_iow.geojson")
```

```{r}
roads_iow = sf::read_sf("https://github.com/ropensci/stplanr/releases/download/0.3.1/roads_iow.geojson")
```

# osrm

```{r, echo=FALSE, eval=FALSE}
if(!file.exists("iow.pbf"))
  download.file("http://download.geofabrik.de/europe/great-britain/england/isle-of-wight-latest.osm.pbf", "iow.pbf")
options(osrm.server = "http://0.0.0.0:5000/", osrm.profile = "driving")
```

Then in bash run the following commands to make the [OSRM docker image](https://hub.docker.com/r/osrm/osrm-backend/) work for you.

```{r, engine='bash', eval=FALSE}
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/iow.pbf
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/iow.osrm
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/iow.osrm
docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/iow.osrm
curl "http://127.0.0.1:5000/route/v1/driving/13.388860,52.517037;13.385983,52.496891?steps=true"
```

Now we can do routing in R!

```{r, eval=FALSE}
l = pct::wight_lines_30
p = line2points(l)
r = osrm::osrmRoute(src = p[1, ], dst = p[2, ], returnclass = "sf")
plot(r)
```

```{r, eval=FALSE}
route_osrm2 = function(l) {
  p = line2points(l)
  s = (1:nrow(l)) * 2 - 1
  list_out = lapply(s, function(i) osrm::osrmRoute(p[i, ], dst = p[i + 1, ], returnclass = "sf"))
  do.call(rbind, list_out)
}
routes_osrm = route_osrm2(l)
plot(routes_osrm)
# tidy up
file.remove("iow.pbf")
```





