// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// coord_matches
List coord_matches(SEXP sldf, double tolval);
RcppExport SEXP _stplanr_coord_matches(SEXP sldfSEXP, SEXP tolvalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sldf(sldfSEXP);
    Rcpp::traits::input_parameter< double >::type tolval(tolvalSEXP);
    rcpp_result_gen = Rcpp::wrap(coord_matches(sldf, tolval));
    return rcpp_result_gen;
END_RCPP
}
// join_spatiallines_coords
arma::mat join_spatiallines_coords(SEXP sldf, double startx, double starty);
RcppExport SEXP _stplanr_join_spatiallines_coords(SEXP sldfSEXP, SEXP startxSEXP, SEXP startySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sldf(sldfSEXP);
    Rcpp::traits::input_parameter< double >::type startx(startxSEXP);
    Rcpp::traits::input_parameter< double >::type starty(startySEXP);
    rcpp_result_gen = Rcpp::wrap(join_spatiallines_coords(sldf, startx, starty));
    return rcpp_result_gen;
END_RCPP
}
// coord_matches_sf
List coord_matches_sf(arma::mat x, arma::mat sortedx, unsigned int sllength, double tolval);
RcppExport SEXP _stplanr_coord_matches_sf(SEXP xSEXP, SEXP sortedxSEXP, SEXP sllengthSEXP, SEXP tolvalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sortedx(sortedxSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type sllength(sllengthSEXP);
    Rcpp::traits::input_parameter< double >::type tolval(tolvalSEXP);
    rcpp_result_gen = Rcpp::wrap(coord_matches_sf(x, sortedx, sllength, tolval));
    return rcpp_result_gen;
END_RCPP
}
// join_spatiallines_coords_sf
arma::mat join_spatiallines_coords_sf(List lines, double startx, double starty);
RcppExport SEXP _stplanr_join_spatiallines_coords_sf(SEXP linesSEXP, SEXP startxSEXP, SEXP startySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type lines(linesSEXP);
    Rcpp::traits::input_parameter< double >::type startx(startxSEXP);
    Rcpp::traits::input_parameter< double >::type starty(startySEXP);
    rcpp_result_gen = Rcpp::wrap(join_spatiallines_coords_sf(lines, startx, starty));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stplanr_coord_matches", (DL_FUNC) &_stplanr_coord_matches, 2},
    {"_stplanr_join_spatiallines_coords", (DL_FUNC) &_stplanr_join_spatiallines_coords, 3},
    {"_stplanr_coord_matches_sf", (DL_FUNC) &_stplanr_coord_matches_sf, 4},
    {"_stplanr_join_spatiallines_coords_sf", (DL_FUNC) &_stplanr_join_spatiallines_coords_sf, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_stplanr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
